---
on:
  pull_request:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: sam build --template sam_template.yaml --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ebook_store_dapp_stack --image-repository 621544995223.dkr.ecr.us-west-2.amazonaws.com/ebook_store_dapp --capabilities CAPABILITY_IAM --region us-west-2
